version: '3.8'

services:
  bot:
    build: .
    container_name: random_coffee_bot
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер
      - ./data:/app/data  # Монтируем папку с базой данных
    environment:
      - TOKEN=${TOKEN}  # Токен бота из переменной окружения
      - ADMIN_ID=${ADMIN_ID}  # ID администратора из переменной окружения
    restart: unless-stopped